### ISSUE TITLE
[Request] List入力時、未入力のまま改行するときはList入力をやめたい

### ISSUE THREAD

**Issue by s-yu-yu-yu** [deren2525/new-tab-note#10]
## 概要

List入力時、改行すると次のItemの入力が始まります。
```
- hoge↩︎
- 
```
このとき未入力のまま改行をすると次のItemの入力が始まります。
```
- hoge↩︎
- ↩︎
- 
```
一般的なマークダウン記法のサポートされたエディタでは、このような入力を行った際はList入力がキャンセルされるはずです。
```
- hoge↩︎
↩︎
```

NEW TAB NOTEでもこのような入力がサポートしていただきたいです。

## もし上記の要望・改善が反映されたらどれくらい喜びますか？

とても喜びます。Twitterで宣伝もします。

## 反映されたら絶対に喜んでくださいね

- [x] はい

**Comment by deren2525** [comment]
遅れました。やります。

**Comment by deren2525** [comment]
@s-yu-yu-yu 
だいぶ反応遅れました。やります。

**Comment by deren2525** [comment]
審査待ち

**Comment by deren2525** [comment]
審査通り反映されたのでクローズ
